version: '3.4'
services:
    sporenstreks-database:
        build:
            context: ./postgres
            dockerfile: postgres.Dockerfile
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
    sporenstreks-backend:
        image: docker.pkg.github.com/navikt/sporenstreks/sporenstreks:55cc79b
        depends_on:
            - sporenstreks-database
        environment:
            - DATABASE_HOST=sporenstreks-database
        ports:
            - "8080:8080"
volumes:
    data:
