version: '3.4'
services:
    sporenstreks-database:
        build:
            context: ./postgres
            dockerfile: postgres.Dockerfile
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
volumes:
    data:
