apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporenstreks
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    periodSeconds: 30
    timeout: 2
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://sporenstreks.nais.adeo.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 5000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/sporenstreks/default
        mountPath: /var/run/secrets/nais.io/vault
      - mountPath: /var/run/secrets/nais.io/apigw/altinn
        kvPath: /apikey/apigw/prod/eksternapp.altinn.serviceowner/sporenstreks
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvsporenstreks
  webproxy: true
  leaderElection: true
  secureLogs:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten # tilgjengeliggjør LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE

  env:
    - name: KOIN_PROFILE
      value: PROD
    - name: DATABASE_HOST
      value: A01DBVL011.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: sporenstreks
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: ALTINN_SERVICE_OWNER_GW_URL
      value: https://api-gw.adeo.no/ekstern/altinn/api/serviceowner
    - name: SECURITYTOKENSERVICE_URL_REST
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: SECURITYTOKENSERVICE_URL_WS
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: DOKARKIV_URL
      value: https://dokarkiv.nais.adeo.no
    - name: AAREG_URL
      value: https://modapp.adeo.no/aareg-services
    - name: AKTOERREGISTER_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: OPPGAVEBEHANDLING_URL
      value: http://oppgave.default.svc.nais.local/api/v1/oppgaver
    - name: PARTNER_GATEWAY_ALTINN_ENDPOINT
      value: https://pep-gw.oera.no:9443/ekstern/altinn/BehandleAltinnMelding/v1
