apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporenstreks
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    periodSeconds: 30
    timeout: 2
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://sporenstreks.nais.adeo.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 5000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/sporenstreks/default
        mountPath: /var/run/secrets/nais.io/vault
      - mountPath: /var/run/secrets/nais.io/apigw/altinn
        kvPath: /apikey/apigw/prod/eksternapp.altinn.serviceowner/sporenstreks
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvsporenstreks
  webproxy: true
  env:
    - name: KOIN_PROFILE
      value: PROD
    - name: DATABASE_HOST
      value: A01DBVL011.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: sporenstreks
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: OIDC_DISCOVERY_URL
      value: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    - name: OIDC_ACCEPTED_AUDIENCE
      value: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
    - name: OIDC_ISSUER_NAME
      value: aadb2c
    - name: ALTINN_SERVICE_OWNER_GW_URL
      value: https://api-gw.adeo.no/ekstern/altinn/api/serviceowner
    - name: SECURITYTOKENSERVICE_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: DOKARKIV_URL
      value: https://dokarkiv.nais.adeo.no
    - name: AKTOERREGISTER_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: OPPGAVEBEHANDLING_URL
      value: http://oppgave.default.svc.nais.local/api/v1/oppgaver
