name: Pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      #      - uses: actions/cache@v1
      #        with:
      #          path: ~/.gradle/caches
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      #          restore-keys: |
      #            ${{ runner.os }}-gradle-
      - name: create docker tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/sporenstreks
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo $(echo $GITHUB_SHA | cut -c1-7) > .docker_tag
      - name: compose up
        run: cd docker/local && docker-compose up -d && sleep 15
      - name: test and build
        run: ./gradlew --console=plain build test slowTests jacocoTestReport sonarqube
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --configuration-matching=runtimeClasspath --fail-on=all


